### ISSUE TITLE
restore schema failed after upgrade to v0.7.5

### ISSUE THREAD

**Issue by Rader** [dgraph-io/dgraph#843]
The data is backup-ed by a custom build from source code before v0.7.4.

```
[root@vm dgraph_bin]# ./dgraphloader_v0.7.5 -r backup/dgraph-1-2017-04-17-10-02.rdf.gz -s backup/dgraph-schema-1-2017-04-17-10-02.rdf.gz

Dgraph version   : v0.7.5
Commit SHA-1     : cea0622
Commit timestamp : 2017-04-12 18:44:27 +1000
Branch           : release/v0.7.5



Processing backup/dgraph-schema-1-2017-04-17-10-02.rdf.gz
2017/04/17 10:11:24 main.go:88: Error while parsing schema: Invalid schema. Unexpected , on line:1 ÿlKrÃ0
                                                                                                          C÷>EÍ¼ÊM4؜ZT¤Üæö+±ÝßN<I¸gܨÎÑÑ}îî߼Lö¾§a9:¥ÞÃDÇÓEñù°|g?wìW±våC±ãÅðbNä)hlç,Z¾ÇVbþ
IÇJã±98m?ñ [;M,Â(I¸mD4ίg¤ë£ÅnÅR. ©aJ!þ§gAÄ¿ø?¸[l(UÞ/ÿÿÿÿ)­xîv
```
I am failed to attach the schema file. Here is the schema in plain text.
```
id:default
act:uid
pid:default
mark:uid @reverse
name:string @index(term)
root:uid
type:default
birth:default
score:default
direct:uid
has_tag:uid
minutes:default
name_en:string @index(term)
language:default
lead_act:uid
starring:uid
video_id:int @index(int)
direct_by:uid
for_movie:uid
watch_times:int @index(int)
release_date:default
lead_starring:uid
release_country:uid
```

**Comment by manishrjain** [comment]
@Rader Can you share this backup with us? You can DM me on Slack. So, we can try to load it up and see what's the issue.

**Comment by janardhan1993** [comment]
@reader: we changed the schema format in 0.7.4. It should be terminated by dot and new line. Since this backup was taken before that version can you add <space><dot> ( .) to every line similar to rdf.

**Comment by Rader** [comment]
@janardhan1993 New error after add "." to each line.

```
2017/04/17 11:28:07 main.go:88: Error while parsing schema: Undefined Type, on line:1 id:default.
```

**Comment by Motakjuq** [comment]
@Rader `default` is not a valid type for the schema. You can see a list of the schema types on [here](https://docs.dgraph.io/v0.7.5/query-language/#schema-types)

**Comment by Rader** [comment]
@Motakjuq It's generated by Dgraph, when I do a backup.

**Comment by janardhan1993** [comment]
Please keep space between type and dot, it should be default<space><dot>

**Comment by janardhan1993** [comment]
@Rader Can you please close the issue if it's fixed.

**Comment by janardhan1993** [comment]
Closing this issue. @Rader  Please feel free to reopen if you still face the issue.

**Comment by Motakjuq** [comment]
@janardhan1993 is a problem with the current implementation in dgraphloader for the schema restoration, it's reading the file as plain text, but the backup file is gzip, for that reason @Rader is getting that error. In this specific case, the schema file is also outdated an it's required to add a `.` at the end of each line.

**Comment by janardhan1993** [comment]
Yeah, it was the case of outdated schema file where . was not mandatory. Thanks for submitting PR for reading gzip schema file.
